### PR TITLE
Fixed an error when the player isnt using the Chestshop

### PR DESCRIPTION
**Pull request by KairusDarkSeeker**
Howbatdat

### CODE REVIEW

**Comment by Muqsit** [comment]
1. There's no use of `==`. It's safe to use `===`.
2. return bool?
3. It depends on $player and not on $action :/

**Comment by KairusDarkSeeker** [comment]
@Muqsit It spams my console lol so I added that

**Comment by Muqsit** [comment]
I'll fix it

**Comment by KairusDarkSeeker** [comment]
@Muqsit lol just merge it

**Comment by Muqsit** [comment]
That's a bad fix

**Comment by KairusDarkSeeker** [comment]
@Muqsit okay then

**Pull request closed without merging**
